---
- name: bootstrap ap server
  hosts: web_server
  become: yes
  roles: 
    - basic_package
    - nginx
    - php72-fpm
  vars:
    Fresh_install: true
    new_user: habibza
    php_version: 7.2
    domain: laravel.habibza.in
    php_fpm_port: 9000
